---
- hosts: example
  become: true
  user: mohammed
  connection: ssh 

  tasks:
  - name: Install apache
    apt: 
      name: {{ item }} 
      state: latest
    with_items:
     - apache2
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  