---
- hosts: example
  become: true
  user: remy
  connection: ssh 

  tasks:
  - name: Install apache
    apt: 
      name: {{ item }} 
      state: latest
    with_items:
     - apache2
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Install httpd
    yum: 
      name: {{ item }} 
      state: latest
    with_items:
     - httpd
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'